networks:
  localnet:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_BASE_PATH}/data/db
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_BASE_PATH}/data/wp


services:
  mariadb:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    pull_policy: never
    env_file: .env
    networks:
      localnet:
        ipv4_address: 172.16.0.5
    volumes:
      - db-volume:/var/lib/mysql/data
    expose:
      - 3306
    restart: unless-stopped
    hostname: "mariadb"

  
  wordpress:
    build: ./wordpress
    image: wordpress
    container_name: wordpress
    pull_policy: never
    env_file: .env
    networks:
      localnet:
        ipv4_address: 172.16.0.7
    volumes:
      - wp-volume:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    restart: unless-stopped
    hostname: "wordpress"

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    pull_policy: never
    networks:
      localnet:
        ipv4_address: 172.16.0.6
    volumes:
      - wp-volume:/var/www/html
    ports:
      - "443:443"
    restart: unless-stopped
    hostname: "nginx"
